-- Macrofunções passam a cobrir também as áreas de atuação controladas (Res. TCM-BA 1.120/2005, art. 12),
-- além das quatro macrofunções da OT 05/2024. Valores só acrescentados: nada existente muda.

ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'PLANEJAMENTO_ORCAMENTO';
ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'CONTABILIDADE_FINANCAS';
ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'GESTAO_FISCAL';
ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'RECEITA';
ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'PESSOAL';
ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'PATRIMONIO';
ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'LICITACOES_CONTRATOS';
ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'OBRAS';
ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'TRANSFERENCIAS';
ALTER TYPE "Macrofuncao" ADD VALUE IF NOT EXISTS 'TRANSPARENCIA';
