export const TOKENS_AMEIXA: { token: string; hex: string; uso: string }[] = [
  { token: "background", hex: "#F8F7FA", uso: "Fundo da página" },
  { token: "foreground", hex: "#1F1A2E", uso: "Texto principal" },
  { token: "card", hex: "#FFFFFF", uso: "Cartões, tabelas, painéis" },
  { token: "card-foreground", hex: "#1F1A2E", uso: "Texto em cartões" },
  { token: "primary", hex: "#5B3A8E", uso: "Botão principal, links, seleção" },
  { token: "primary-foreground", hex: "#FFFFFF", uso: "Texto sobre a primária" },
  { token: "secondary", hex: "#EEE9F6", uso: "Botão secundário, etiquetas neutras" },
  { token: "secondary-foreground", hex: "#3D2766", uso: "Texto sobre a secundária" },
  { token: "muted", hex: "#F1EFF5", uso: "Áreas de apoio, cabeçalho de tabela" },
  { token: "muted-foreground", hex: "#5D5770", uso: "Texto secundário" },
  { token: "accent", hex: "#EAE4F5", uso: "Item em foco, hover, linha selecionada" },
  { token: "accent-foreground", hex: "#3D2766", uso: "Texto sobre accent" },
  { token: "destaque", hex: "#3EC6D9", uso: "Cor de marca: indicador ativo, IA, selo" },
  { token: "destaque-foreground", hex: "#0A2A31", uso: "Texto sobre o destaque" },
  { token: "sucesso", hex: "#1E7A4C", uso: "Atende, concluída" },
  { token: "alerta", hex: "#9A5A00", uso: "Parcial, em análise, prazo próximo" },
  { token: "perigo", hex: "#C0262D", uso: "Não atende, vencida, atrasada" },
  { token: "info", hex: "#1D62B5", uso: "Enviada, em andamento" },
  { token: "border", hex: "#E3DFEA", uso: "Bordas de cartões e divisórias" },
  { token: "input", hex: "#948DA6", uso: "Borda de campos (contraste 3:1)" },
  { token: "ring", hex: "#7B57C7", uso: "Contorno de foco" },
  { token: "sidebar", hex: "#2B2045", uso: "Barra de navegação superior" },
  { token: "sidebar-foreground", hex: "#ECE8F5", uso: "Texto da navegação" },
  { token: "sidebar-primary", hex: "#3EC6D9", uso: "Indicador do item ativo" },
  { token: "sidebar-accent", hex: "#3B2E5E", uso: "Hover e busca na navegação" },
  { token: "sidebar-border", hex: "#43366A", uso: "Divisórias na navegação" },
  { token: "chart-1", hex: "#5B3A8E", uso: "Gráficos — série 1" },
  { token: "chart-2", hex: "#3EC6D9", uso: "Gráficos — série 2" },
  { token: "chart-3", hex: "#D9822B", uso: "Gráficos — série 3" },
  { token: "chart-4", hex: "#1E7A4C", uso: "Gráficos — série 4" },
  { token: "chart-5", hex: "#C0262D", uso: "Gráficos — série 5" },
];

export const OUTROS_TOKENS_AMEIXA = [
  { token: "radius", valor: "6 px (0.375rem)", uso: "Raio de canto base" },
  { token: "sombra-sm", valor: "0 1px 2px rgb(31 26 46 / 6%)", uso: "Cartões e campos" },
  { token: "sombra-md", valor: "0 4px 14px rgb(31 26 46 / 8%)", uso: "Menus, diálogos, painéis flutuantes" },
  { token: "Fonte de texto", valor: "Atkinson Hyperlegible Next", uso: "Textos, títulos e interface" },
  { token: "Fonte de títulos", valor: "Atkinson Hyperlegible Next (700)", uso: "Mesma família, em negrito" },
  { token: "Fonte de códigos", valor: "Atkinson Hyperlegible Mono", uso: "Números, datas, códigos de requisitos" },
];
